{"name":"Execute some hook before scenario outline","id":"exceptions-in-cucumber-hooks-must-result-in-failed-scenario-execution;execute-some-hook-before-scenario-outline","testSteps":[{"number":1,"description":"Execute some hook before scenario outline #1: {number\u003d1}","duration":12,"startTime":"2018-03-08T16:07:59.748+01:00[Europe/Vienna]","exception":{"errorType":"java.lang.RuntimeException","message":"Oops! Some exception happened during hook execution!","stackTrace":[{"declaringClass":"steps.hooks.TestHooks","methodName":"setup","fileName":"TestHooks.java","lineNumber":11},{"declaringClass":"cucumber.runner.UnskipableStep","methodName":"executeStep","fileName":"UnskipableStep.java","lineNumber":22},{"declaringClass":"cucumber.runner.Runner","methodName":"runPickle","fileName":"Runner.java","lineNumber":80}]},"result":"ERROR","precondition":false,"children":[{"number":2,"description":"Given 1 scenarios with some before hook","duration":0,"startTime":"2018-03-08T16:07:59.752+01:00[Europe/Vienna]","result":"IGNORED","precondition":false},{"number":3,"description":"When an exception happens during hook execution","duration":1,"startTime":"2018-03-08T16:07:59.753+01:00[Europe/Vienna]","result":"IGNORED","precondition":false},{"number":4,"description":"Then the steps should have status Ignored","duration":0,"startTime":"2018-03-08T16:07:59.754+01:00[Europe/Vienna]","result":"IGNORED","precondition":false},{"number":5,"description":"But the scenario should be reported as Failing","duration":0,"startTime":"2018-03-08T16:07:59.755+01:00[Europe/Vienna]","result":"IGNORED","precondition":false}]},{"number":6,"description":"Execute some hook before scenario outline #2: {number\u003d2}","duration":9,"startTime":"2018-03-08T16:07:59.812+01:00[Europe/Vienna]","exception":{"errorType":"java.lang.RuntimeException","message":"Oops! Some exception happened during hook execution!","stackTrace":[{"declaringClass":"steps.hooks.TestHooks","methodName":"setup","fileName":"TestHooks.java","lineNumber":11},{"declaringClass":"cucumber.runner.UnskipableStep","methodName":"executeStep","fileName":"UnskipableStep.java","lineNumber":22},{"declaringClass":"cucumber.runner.Runner","methodName":"runPickle","fileName":"Runner.java","lineNumber":80}]},"result":"ERROR","precondition":false,"children":[{"number":7,"description":"Given 2 scenarios with some before hook","duration":1,"startTime":"2018-03-08T16:07:59.815+01:00[Europe/Vienna]","result":"SKIPPED","precondition":false},{"number":8,"description":"When an exception happens during hook execution","duration":1,"startTime":"2018-03-08T16:07:59.816+01:00[Europe/Vienna]","result":"SKIPPED","precondition":false},{"number":9,"description":"Then the steps should have status Ignored","duration":1,"startTime":"2018-03-08T16:07:59.817+01:00[Europe/Vienna]","result":"SKIPPED","precondition":false},{"number":10,"description":"But the scenario should be reported as Failing","duration":1,"startTime":"2018-03-08T16:07:59.818+01:00[Europe/Vienna]","result":"SKIPPED","precondition":false}]}],"userStory":{"id":"exceptions-in-cucumber-hooks-must-result-in-failed-scenario-execution","storyName":"Exceptions in cucumber hooks must result in failed scenario execution","path":"test.feature","type":"feature"},"featureTag":{"name":"Exceptions in cucumber hooks must result in failed scenario execution","type":"feature"},"title":"Execute some hook before scenario outline","tags":[{"name":"Bug","type":"tag"},{"name":"Exceptions in cucumber hooks must result in failed scenario execution","type":"feature"}],"startTime":"2018-03-08T16:07:59.747+01:00[Europe/Vienna]","duration":677,"testFailureCause":{"errorType":"java.lang.RuntimeException","message":"Oops! Some exception happened during hook execution!","stackTrace":[{"declaringClass":"steps.hooks.TestHooks","methodName":"setup","fileName":"TestHooks.java","lineNumber":11},{"declaringClass":"cucumber.runner.UnskipableStep","methodName":"executeStep","fileName":"UnskipableStep.java","lineNumber":22},{"declaringClass":"cucumber.runner.Runner","methodName":"runPickle","fileName":"Runner.java","lineNumber":80}]},"testFailureClassname":"java.lang.RuntimeException","testFailureMessage":"Oops! Some exception happened during hook execution!","testFailureSummary":"ERROR;java.lang.RuntimeException;Oops! Some exception happened during hook execution!;TestHooks.java","projectKey":"","annotatedResult":"ERROR","dataTable":{"headers":["number"],"rows":[{"values":["1"],"result":"ERROR"},{"values":["2"],"result":"ERROR"}],"predefinedRows":true,"scenarioOutline":"Given \u003cnumber\u003e scenarios with some before hook\n\rWhen an exception happens during hook execution\n\rThen the steps should have status Ignored\n\rBut the scenario should be reported as Failing\n\r","dataSetDescriptors":[{"startRow":0,"rowCount":0,"name":""}]},"manual":false,"testSource":"Cucumber","result":"ERROR"}